#!/usr/bin/env python3
"""Generate a 256-level Jet rainbow colour LUT for the GeoScatter3D fragment shader.

Usage:
  python3 tools/generate_rainbow256_lut.py

Outputs:
  - Prints the GLSL array literal to stdout (for pasting into point.frag)
  - Writes docs/rainbow256_lut.csv as a verification table (index, R, G, B, hex)

Colour formula: classic MATLAB Jet (blue → cyan → green → yellow → red).

To change the colour scheme (e.g. to a different "standard rainbow"), edit the
jet_r(), jet_g(), jet_b() functions below, re-run the script, and paste the new
LUT into the shader.  The shader structure (256-entry array + discrete lookup)
stays the same.
"""

import math
import sys
from pathlib import Path


# ── Classic MATLAB Jet component functions ─────────────────────────────
# t ∈ [0, 1] → channel ∈ [0, 1]
#
# These are the "control knobs" — if the reviewer wants a different
# "standard rainbow", change these three functions and regenerate.


def jet_r(t: float) -> float:
    """Red channel of classic Jet."""
    return max(0.0, min(1.0, min(4.0 * t - 1.5, -4.0 * t + 4.5)))


def jet_g(t: float) -> float:
    """Green channel of classic Jet."""
    return max(0.0, min(1.0, min(4.0 * t - 0.5, -4.0 * t + 3.5)))


def jet_b(t: float) -> float:
    """Blue channel of classic Jet."""
    return max(0.0, min(1.0, min(4.0 * t + 0.5, -4.0 * t + 2.5)))


# ── LUT generation ─────────────────────────────────────────────────────

N = 256


def generate_lut():
    """Return list of (r, g, b) tuples for k = 0 .. N-1."""
    lut = []
    for k in range(N):
        t = k / (N - 1)  # 0, 1/255, 2/255, ..., 255/255 = 1
        lut.append((jet_r(t), jet_g(t), jet_b(t)))
    return lut


# ── GLSL output ─────────────────────────────────────────────────────────

def fmt_glsl_float(v: float) -> str:
    """Format a float so GLSL always sees a valid float literal (e.g. 0.0, not 0)."""
    # Always include a decimal point and at least one fractional digit.
    s = f"{v:.8f}"
    # Trim trailing zeros, but keep at least one fractional digit.
    if "." in s:
        int_part, frac_part = s.split(".", 1)
        frac_part = frac_part.rstrip("0")
        if not frac_part:
            frac_part = "0"
        s = f"{int_part}.{frac_part}"
    return s


def fmt_glsl_vec3(r: float, g: float, b: float) -> str:
    return f"vec3({fmt_glsl_float(r)}, {fmt_glsl_float(g)}, {fmt_glsl_float(b)})"


def print_glsl(lut):
    """Print the GLSL `const vec3 kRainbow256[256]` array."""
    print("// 256-level Jet rainbow LUT — 256 discrete entries, no interpolation.")
    print("// Generated by tools/generate_rainbow256_lut.py")
    print("const vec3 kRainbow256[256] = vec3[256](")
    for k, (r, g, b) in enumerate(lut):
        comma = "," if k < N - 1 else ""
        entry = f"    {fmt_glsl_vec3(r, g, b)}{comma}  // {k:3d}"
        print(entry)
    print(");")


# ── CSV verification table ──────────────────────────────────────────────

def write_csv(lut, path: Path):
    """Write docs/rainbow256_lut.csv — one row per LUT entry."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("index,R_norm,G_norm,B_norm,R_8bit,G_8bit,B_8bit,hex\n")
        for k, (r, g, b) in enumerate(lut):
            ri = round(r * 255)
            gi = round(g * 255)
            bi = round(b * 255)
            hex_code = f"#{ri:02X}{gi:02X}{bi:02X}"
            f.write(f"{k},{r:.8g},{g:.8g},{b:.8g},{ri},{gi},{bi},{hex_code}\n")
    print(f"\n// Verification table written to: {path}", file=sys.stderr)


# ── main ────────────────────────────────────────────────────────────────

def main():
    repo_root = Path(__file__).resolve().parent.parent
    lut = generate_lut()

    # 1. Print GLSL array to stdout (for copy-paste into point.frag)
    print_glsl(lut)

    # 2. Write CSV verification table
    csv_path = repo_root / "docs" / "rainbow256_lut.csv"
    write_csv(lut, csv_path)


if __name__ == "__main__":
    main()
